name: sanai3i
description: A new sanai3i app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  get:
  get_storage:
  flutter_bloc:
  firebase_core: 
  firebase_messaging: 
  firebase_auth: 
  cloud_firestore: 
  flutter_local_notifications: 
  connectivity_plus:
  country_code_picker:
  lottie:
  pinput:
  animated_bottom_navigation_bar:
  animate_icons: 
  qr_code_scanner: 
  qr_flutter: 
  google_maps_flutter:
  geolocator:
  geoflutterfire: ^3.0.3
  cached_network_image: 
  carousel_slider:
  flutter_staggered_grid_view:
  shimmer:
  rxdart:
  url_launcher:



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  flutter_lints:
  json_serializable:
  freezed_annotation:
  flutter_native_splash:      #  flutter pub run flutter_native_splash:create
  flutter_launcher_icons:     #  flutter pub run flutter_launcher_icons:main
  change_app_package_name:    #  flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/icon.png"


flutter_native_splash:
  background_image: "assets/launcher/logo.png"
  fullscreen: true
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/
    - assets/animations/

  fonts:
  - family: font
    fonts:
      - asset: assets/fonts/Taj.ttf
        weight: 500
