// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCQLO0tv4lR_f7ab-9d_XlIRuTQZ-ceI',
    appId: '1:905314520718:web:46e3487bb7318b691343df',
    messagingSenderId: '905314520718',
    projectId: 'sanai3i-9951b',
    authDomain: 'sanai3i-9951b.firebaseapp.com',
    databaseURL: 'https://sanai3i-9951b.firebaseio.com',
    storageBucket: 'sanai3i-9951b.appspot.com',
    measurementId: 'G-FEBLK3FG14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjiSQq1yucYu8eypHhgIlBlX1XSw68zY',
    appId: '1:905314520718:android:26e75660c3906f791343df',
    messagingSenderId: '905314520718',
    projectId: 'sanai3i-9951b',
    databaseURL: 'https://sanai3i-9951b.firebaseio.com',
    storageBucket: 'sanai3i-9951b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-zz7HvGCTGxGdYMjWv7U1OHZQfG2hOE',
    appId: '1:905314520718:ios:6dd170fbf1d39e771343df',
    messagingSenderId: '905314520718',
    projectId: 'sanai3i-9951b',
    databaseURL: 'https://sanai3i-9951b.firebaseio.com',
    storageBucket: 'sanai3i-9951b.appspot.com',
    androidClientId: '905314520718-1mllhibp95k2dm451rf26u0hel493f27.apps.googleusercontent.com',
    iosClientId: '905314520718-3pvvdu284u409fk34aoqp4e1pind2jlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSanai3i',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-zz7HvGCTGxGdYMjWv7U1OHZQfG2hOE',
    appId: '1:905314520718:ios:6dd170fbf1d39e771343df',
    messagingSenderId: '905314520718',
    projectId: 'sanai3i-9951b',
    databaseURL: 'https://sanai3i-9951b.firebaseio.com',
    storageBucket: 'sanai3i-9951b.appspot.com',
    androidClientId: '905314520718-1mllhibp95k2dm451rf26u0hel493f27.apps.googleusercontent.com',
    iosClientId: '905314520718-3pvvdu284u409fk34aoqp4e1pind2jlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newSanai3i',
  );
}
